models/Patrocinadores.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "patrocinadores".
 *
 * @property int $codigo
 * @property string $nombre
 * @property float|null $cantidad_aportada
 * @property string|null $dni_directivo
 * @property string|null $temporada_ini
 * @property string|null $temporada_fin
 *
 * @property Directivos $dniDirectivo
 * @property Patrocinios[] $patrocinios
 * @property Barcos[] $matriculaBarcos
 * @property Remeros[] $remeros
 */
class Patrocinadores extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'patrocinadores';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nombre','dni_directivo','cantidad_aportada'], 'required'],
            [['cantidad_aportada'], 'number'],
            [['nombre'], 'string', 'max' => 30],
            [['dni_directivo'], 'string', 'max' => 9],
            [['temporada_ini', 'temporada_fin'], 'string', 'max' => 4],
            [['dni_directivo'], 'exist', 'skipOnError' => true, 'targetClass' => Directivos::className(), 'targetAttribute' => ['dni_directivo' => 'dni']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'codigo' => 'Código',
            'nombre' => 'Nombre',
            'cantidad_aportada' => 'Cantidad Aportada',
            'dni_directivo' => '    Directivo',
            'temporada_ini' => 'Temporada Inicio',
            'temporada_fin' => 'Temporada Fin',
        ];
    }

    /**
     * Gets query for [[DniDirectivo]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDniDirectivo()
    {
        return $this->hasOne(Directivos::className(), ['dni' => 'dni_directivo']);
    }

    /**
     * Gets query for [[Patrocinios]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPatrocinios()
    {
        return $this->hasMany(Patrocinios::className(), ['codigo_patrocinador' => 'codigo']);
    }

    /**
     * Gets query for [[MatriculaBarcos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getMatriculaBarcos()
    {
        return $this->hasMany(Barcos::className(), ['matricula' => 'matricula_barco'])->viaTable('patrocinios', ['codigo_patrocinador' => 'codigo']);
    }

    /**
     * Gets query for [[Remeros]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getRemeros()
    {
        return $this->hasMany(Remeros::className(), ['codigo_patrocinador' => 'codigo']);
    }
}

controllers/PatrocinadoresController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Patrocinadores;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Directivos;

/**
 * PatrocinadoresController implements the CRUD actions for Patrocinadores model.
 */
class PatrocinadoresController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Patrocinadores models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Patrocinadores::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Patrocinadores model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Patrocinadores model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Patrocinadores();
        $modeldirectivos = Directivos::find()->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->codigo]);
        }

        return $this->render('create', [
            'model' => $model,
            'modeldirectivos' => $modeldirectivos,
        ]);
    }

    /**
     * Updates an existing Patrocinadores model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $modeldirectivos = Directivos::find()->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->codigo]);
        }

        return $this->render('update', [
            'model' => $model,
            'modeldirectivos' => $modeldirectivos,
        ]);
    }

    /**
     * Deletes an existing Patrocinadores model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Patrocinadores model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Patrocinadores the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Patrocinadores::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Remeros;
use app\models\Entrenadores;
use app\models\Patrocinadores;
use app\models\Barcos;
use app\models\Remos;
use app\models\Gastos;
use app\models\Cuotas;


class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        
        $numremeros = Remeros::find()->count();
        $numentrenadores = Entrenadores::find()->count();
        $numpatrocinadores = Patrocinadores::find()->count();
        $numbarcos = Barcos::find()->count();
        $numremos = Remos::find()->count();
        
        return $this->render('index',
                [
                    'numremeros' => $numremeros,
                    'numentrenadores' => $numentrenadores,
                    'numpatrocinadores' => $numpatrocinadores,
                    'numbarcos' => $numbarcos,
                    'numremos' => $numremos,
                ]);
    }
    
    public function actionTesoreria()
    {
        $cantgastos = Gastos::find()->sum('cantidad');
        $cantcuotas = Cuotas::find()->sum('importe');
        $cantpatrocinadores = Patrocinadores::find()->sum('cantidad_aportada');
        
 
        return $this->render('tesoreria', [
            'cantgastos' => $cantgastos,
            'cantcuotas' => $cantcuotas,
            'cantpatrocinadores' => $cantpatrocinadores,
        ]);
    } 

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/patrocinadores/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\Patrocinadores */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="patrocinadores-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'cantidad_aportada')->textInput(['type' => 'number']) ?>
    
    <?php 
        $listdirectivos= ArrayHelper::map($modeldirectivos,'dni','nombre_completo');
    ?>
    
    <?= $form->field($model, 'dni_directivo')->dropDownList($listdirectivos,['prompt' => 'Directivo que lo contrata'])->label('Nombre del directivo') ?>

    <?= $form->field($model, 'temporada_ini')->textInput(['maxlength' => true, 'type' => 'number'])->label('Temporada de inicio del contrato') ?>

    <?= $form->field($model, 'temporada_fin')->textInput(['maxlength' => true, 'type' => 'number'])->label('Temporada de fin del contrato') ?>

    <div class="botonesadd">
        <?= Html::a('VOLVER A PATROCINADORES', ['/patrocinadores/index'], ['class' => 'btn btn-primary']) ?>
        <?= Html::submitButton('GUARDAR', ['class' => 'btn btn-primary']) ?>
        
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/patrocinadores/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Patrocinadores */

$this->title = 'Nuevo Patrocinador';
$this->params['breadcrumbs'][] = ['label' => 'Patrocinadores', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="patrocinadores-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'modeldirectivos' => $modeldirectivos,
    ]) ?>

</div>

views/patrocinadores/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Patrocinadores';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="indexmodel">
    
    <div class="cat-header">  
     
        <div class="col-lg-12">
            <?php 
                echo Html::a(
                        Html::img(
                                '@web/images/bg-patrocinios.jpg', 
                                ['class' => 'img-responsive img-border']
                        ),
                                ['patrocinios/index']
                    ); 
            ?>
        </div>
    
    </div>

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            [
                'attribute' => 'Patrocinador',
                'value' => 'nombre',
            ],
            'cantidad_aportada',
            'temporada_ini',
            'temporada_fin',
            [
                    'attribute' => 'Barcos patrocinados',
                    'value' => function($model) {
                               return join(', ', ArrayHelper::map($model->matriculaBarcos, 'matricula', 'mote'));
                    },
            ],
            [
                    'attribute' => 'Remero apadrinado',
                    'value' => function($model) {
                               return join(', ', ArrayHelper::map($model->remeros, 'codigo_patrocinador', 'nombre_completo'));
                    },
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    
    <p class="botonesadd">
        <?= Html::a('VOLVER A TESORERÍA', ['site/tesoreria'], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('AÑADIR PATROCINADOR', ['create'], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('AÑADIR PATROCINIO', ['patrocinios/create'], ['class' => 'btn btn-primary']) ?>
    </p>



</div>

views/patrocinadores/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Patrocinadores */

$this->title = 'Editar patrocinador ' . $model->nombre;
$this->params['breadcrumbs'][] = ['label' => 'Patrocinadores', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->nombre, 'url' => ['view', 'id' => $model->codigo]];
$this->params['breadcrumbs'][] = 'Editar';
?>
<div class="patrocinadores-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'modeldirectivos' => $modeldirectivos,
    ]) ?>

</div>

views/patrocinadores/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Patrocinadores */

$this->title = $model->nombre;
$this->params['breadcrumbs'][] = ['label' => 'Patrocinadores', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="patrocinadores-view">

    <h1><?= Html::encode($this->title) ?></h1>

    
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'nombre',
            'cantidad_aportada',
            [
                'attribute' => 'Directivo',
                'value' => $model->dniDirectivo['nombre_completo'],
            ],
            'temporada_ini',
            'temporada_fin',
        ],
    ]) ?>
    
    <p class="botonesadd">
        <?= Html::a('VOLVER A PATROCINADORES', ['/patrocinadores/index'], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('EDITAR', ['update', 'id' => $model->codigo], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('ELIMINAR', ['delete', 'id' => $model->codigo], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => '¿Seguro que quieres eliminar este patrocinador?',
                'method' => 'post',
            ],
        ]) ?>        
    </p>


</div>