models/Categorias.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "categorias".
 *
 * @property string $codigo
 * @property string $nombre
 * @property string $rango_edad
 * @property int|null $num_remeros
 *
 * @property Entrenadores[] $entrenadores
 * @property Remeros[] $remeros
 * @property Usosmaterial[] $usosmaterials
 */
class Categorias extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'categorias';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['codigo', 'nombre', 'rango_edad'], 'required'],
            [['num_remeros'], 'integer'],
            [['codigo'], 'string', 'max' => 2],
            [['nombre'], 'string', 'max' => 35],
            [['rango_edad'], 'string', 'max' => 5],
            [['codigo'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'codigo' => 'Código',
            'nombre' => 'Nombre',
            'rango_edad' => 'Rango de edad',
            'num_remeros' => 'Número de remeros',
        ];
    }

    /**
     * Gets query for [[Entrenadores]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getEntrenadores()
    {
        return $this->hasMany(Entrenadores::className(), ['codigo_categoria' => 'codigo']);
    }

    /**
     * Gets query for [[Remeros]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getRemeros()
    {
        return $this->hasMany(Remeros::className(), ['codigo_categoria' => 'codigo']);
    }

    /**
     * Gets query for [[Usosmaterials]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUsosmaterials()
    {
        return $this->hasMany(Usosmaterial::className(), ['codigo_categoria' => 'codigo']);
    }
}

controllers/CategoriasController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Categorias;
use app\models\Remeros;
use app\models\Entrenadores;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\mpdf\Pdf;


/**
 * CategoriasController implements the CRUD actions for Categorias model.
 */
class CategoriasController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Categorias models.
     * @return mixed
     */
    public function actionIndex()
    {
        $numremeros = Remeros::find()->count();
        $numentrenadores = Entrenadores::find()->count();
        
  
        
        $dataProvider = new ActiveDataProvider([
            'query' => Categorias::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'numremeros' => $numremeros,
            'numentrenadores' => $numentrenadores,
        ]);
    }

    /**
     * Displays a single Categorias model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Categorias model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Categorias();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->codigo]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }
    
    public function actionPdf($codigo) {
    //Consulta remeros
    $remeros= new ActiveDataProvider([
           'query'=>Remeros::find()
                ->select("codigo_remero,nombre_completo,dni")
                ->where("codigo_categoria='$codigo'"),
        ]);
    
    //Consulta entrenadores    
    $entrenadores= new ActiveDataProvider([
       'query'=>Entrenadores::find()->select('nombre_completo,dni')
            ->where("codigo_categoria='$codigo'")
    ]);
    // Renderizo los datros en la vista de remeroscategoria
    $content = $this->renderPartial('remerospdf',[
            "entrenadores" => $entrenadores,
            "campos_entrenadores" => ['nombre_completo','dni'],
            "titulo_entrenadores" => "El entrenador de la categoría ".$codigo." es: ",
            "remeros"=>$remeros,
            "campos_remeros"=>['codigo_remero','nombre_completo','dni'],
            "titulo_remeros"=>"Los remeros que la componen son:",
            "codigo" => $codigo,
    ]);
    // setup kartik\mpdf\Pdf component
    $remerosporcategoria = new Pdf([
        // set to use core fonts only
        'mode' => Pdf::MODE_CORE, 
        // A4 paper format
        'format' => Pdf::FORMAT_A4, 
        // portrait orientation
        'orientation' => Pdf::ORIENT_PORTRAIT, 
        // stream to browser inline
        'destination' => Pdf::DEST_BROWSER, 
        // your html content input
        'content' => $content,  
        'cssInline' => '.kv-heading-1{font-size:18px}', 
         // set mPDF properties on the fly
        'options' => ['title' => 'Krajee Report Title'],
         // call mPDF methods on the fly
        'methods' => [ 
            'SetHeader'=>['Rowwwing APP'], 
            'SetFooter'=>['{PAGENO}'],
        ]
    ]);
    
    return $remerosporcategoria->render(); 

    }

    /**
     * Updates an existing Categorias model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->codigo]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Categorias model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
    public function actionRemerosporcategoria($codigo) {
        
        $remeros= new ActiveDataProvider([
           'query'=>Remeros::find()
                ->select("codigo_remero,nombre_completo,dni")
                ->where("codigo_categoria='$codigo'"),
        ]);
        
        
        $entrenadores= new ActiveDataProvider([
           'query'=>Entrenadores::find()->select('nombre_completo,dni')
                ->where("codigo_categoria='$codigo'")
        ]);
        
        return $this->render("remeroscategoria",[
            "entrenadores" => $entrenadores,
            "campos_entrenadores" => ['nombre_completo','dni'],
            "titulo_entrenadores" => "El entrenador de la categoría ".$codigo." es: ",
            
            "remeros"=>$remeros,
            "campos_remeros"=>['codigo_remero','nombre_completo','dni'],
            "titulo_remeros"=>"Los remeros que la componen son:",
            
            
            "codigo" => $codigo,
        ]);
        
    }

    /**
     * Finds the Categorias model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Categorias the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Categorias::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/RemerosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Remeros;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Categorias;
use app\models\Patrocinadores;
use kartik\mpdf\Pdf;

/**
 * RemerosController implements the CRUD actions for Remeros model.
 */
class RemerosController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Remeros models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Remeros::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Remeros model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Remeros model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Remeros();
        $modelcategorias = Categorias::find()->all();
        $modelpatrocinadores = Patrocinadores::find()->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_remero]);
        }

        return $this->render('create', [
            'model' => $model,
            'modelcategorias' => $modelcategorias,
            'modelpatrocinadores' => $modelpatrocinadores,
        ]);
    }

    /**
     * Updates an existing Remeros model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $modelcategorias = Categorias::find()->all();
        $modelpatrocinadores = Patrocinadores::find()->all();
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_remero]);
        }

        return $this->render('update', [
            'model' => $model,
            'modelcategorias' => $modelcategorias,
            'modelpatrocinadores' => $modelpatrocinadores,           
        ]);
    }

    /**
     * Deletes an existing Remeros model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Remeros model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Remeros the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Remeros::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    
    
 
    public function actionPdf() {
    // get your HTML raw content without any layouts or scripts
    $content = $this->renderPartial('//site/index');
    
    // setup kartik\mpdf\Pdf component
    $pdf = new Pdf([
        // set to use core fonts only
        'mode' => Pdf::MODE_CORE, 
        // A4 paper format
        'format' => Pdf::FORMAT_A4, 
        // portrait orientation
        'orientation' => Pdf::ORIENT_PORTRAIT, 
        // stream to browser inline
        'destination' => Pdf::DEST_BROWSER, 
        // your html content input
        'content' => $content,  
        // format content from your own css file if needed or use the
        // enhanced bootstrap css built by Krajee for mPDF formatting 
        'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
        // any css to be embedded if required
        'cssInline' => '.kv-heading-1{font-size:18px}', 
         // set mPDF properties on the fly
        'options' => ['title' => 'Krajee Report Title'],
         // call mPDF methods on the fly
        'methods' => [ 
            'SetHeader'=>['Krajee Report Header'], 
            'SetFooter'=>['{PAGENO}'],
        ]
    ]);
    
    return $pdf->render(); 

    
    }
    
}

views/categorias/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Categorias */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="categorias-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'codigo')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'rango_edad')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'num_remeros')->textInput() ?>

    <div class="botonesadd">
        <?= Html::submitButton('GUARDAR', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/categorias/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Categorias */

$this->title = 'Nueva Categorias';
$this->params['breadcrumbs'][] = ['label' => 'Categorias', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="categorias-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/categorias/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Categorias';
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="cat-header">  
     
    <div class="col-lg-6">
        <?php 
            echo Html::a(
                    Html::img(
                            '@web/images/bg-remeros.jpg', 
                            ['class' => 'img-responsive img-border']
                    ),
                            ['remeros/index']
                ); 
        ?>
    </div>
    
    <div class="col-lg-6">
        <?php 
            echo Html::a(
                    Html::img(
                            '@web/images/bg-entrenadores.jpg', 
                            ['class' => 'img-responsive img-border']
                    ),
                            ['entrenadores/index']
                ); 
        ?>
    </div>
    
</div>

<div  class="indexmodel">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'nombre',
            'codigo',
            [
                'attribute' => 'Rango de edad',
                'value' => 'rango_edad'
            ],                       
            [
                'attribute' => 'Remeros',
                'value' => 'num_remeros'
            ],
            ['class' => 'yii\grid\ActionColumn',
                 'header' =>'Componentes',
                 'template' => '{remeros}',
                 'buttons' => [
                     'remeros' => function($url, $model) {
                        return Html::a('+info', ['categorias/remerosporcategoria', 'codigo' => $model->codigo], 
                                ['class' => 'btn btn-primary btn-md']);
                     },
                 ],
             ],
            
        ],
    ]); ?>
    
    <p class="botonesadd">
        <?= Html::a('AÑADIR REMERO', ['/remeros/create'], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('AÑADIR ENTRENADOR', ['/entrenadores/create'], ['class' => 'btn btn-primary']) ?>
    </p>


</div>

views/categorias/remeroscategoria.php
<?php
    use yii\grid\GridView;
    use yii\helpers\Html;
    
    $this->title = 'Remeros de la categoria '.$codigo;
    $this->params['breadcrumbs'][] = ['label' => 'Categorias', 'url' => ['index']];
    $this->params['breadcrumbs'][] = $this->title;
 ?>

<div class="indexmodel">
    
    <h2>
        <?= $titulo_entrenadores ?>
    </h2>

    <?= GridView::widget([
        'dataProvider'=>$entrenadores,
        'columns'=>$campos_entrenadores,
    ]); ?>

    
    <h2>
        <?= $titulo_remeros ?>
    </h2>

    <?= GridView::widget([
        'dataProvider'=>$remeros,
        'columns'=>$campos_remeros,
    ]); ?>
    
</div>

<p class="botonesadd">
    <?= Html::a('VOLVER A CATEGORIAS', ['/categorias/index'], ['class' => 'btn btn-primary']) ?>
    <?= Html::a('GENERAR PDF', ['categorias/pdf','codigo' => $codigo], ['class' => 'btn btn-primary']) ?>
</p>

views/categorias/remerospdf.php
<?php
    use yii\grid\GridView;
    
    $this->title = 'Remeros de la categoria '.$codigo;
    $this->params['breadcrumbs'][] = ['label' => 'Categorias', 'url' => ['index']];
    $this->params['breadcrumbs'][] = $this->title;
 ?>

<div class="indexmodel">
    
    <h2>
        <?= $titulo_entrenadores ?>
    </h2>

    <?= GridView::widget([
        'dataProvider'=>$entrenadores,
        'columns'=>$campos_entrenadores,
    ]); ?>

    
    <h2>
        <?= $titulo_remeros ?>
    </h2>

    <?= GridView::widget([
        'dataProvider'=>$remeros,
        'columns'=>$campos_remeros,
    ]); ?>
   
</div>

views/categorias/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Categorias */

$this->title = 'Update Categorias: ' . $model->nombre;
$this->params['breadcrumbs'][] = ['label' => 'Categorias', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->nombre, 'url' => ['view', 'id' => $model->codigo]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="categorias-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/categorias/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Categorias */

$this->title = $model->nombre;
$this->params['breadcrumbs'][] = ['label' => 'Categorias', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="categorias-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->codigo], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->codigo], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => '¿Seguro quieres eliminar esta categoria?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'codigo',
            'nombre',
            'rango_edad',
            'num_remeros',
        ],
    ]) ?>

</div>